blogs/urls.py
from django.urls import path
from .views import index, detail_article, about_me, best_in_month

app_name = "blog"
urlpatterns = [
    path('', index, name="index"),
    path('page/<int:page>', index, name="index"),
    path('article/<slug:slug>', detail_article, name="article_detail"),
    path('best_in_month/', best_in_month, name="best_in_month"),
    path('about_me/', about_me, name="about_me"),
]

my_web/urls.py
from django.contrib import admin
from django.urls import path, include
from blogs import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogs.urls')),
    path('ckeditor', include('ckeditor_uploader.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogs/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from extensions.utils import jalali_converter
from django.utils.html import format_html
from ckeditor_uploader.fields import RichTextUploadingField


# managers
class ArtManager(models.Manager):
    def published(self):
        return self.filter(status='p')

    def monthly_publish(self):
        return self.filter(best_status='y')

    class Meta:
        verbose_name = 'کتگوری '
        verbose_name_plural = 'کتگوری ها'

    def __str__(self):
        return self.title


class IPAddress(models.Model):
    user_ip = models.GenericIPAddressField(verbose_name="user_ip")

    def __str__(self):
        return self.user_ip


class Article(models.Model):
    STATUS_CHOICES = (
        ('d', 'پیش نویس'),
        ('p', "منتشر شده"),
    )
    BEST_STATUS_CHOICES = (
            ('n', 'نیست'),
            ('y', "هست"),
    )
    title = models.CharField(
            max_length=200,
            verbose_name='عنوان مقاله',
            null=True,
    )

    slug = models.SlugField(
            max_length=100, unique=True,
            verbose_name='ادرس مقاله',
            null=True,
    )

    description_img = models.TextField(
        blank=False,
        verbose_name='متن زیر عکس'
    )
    description = RichTextUploadingField(
        verbose_name='متن مقاله'
    )

    ve_thumbnail = models.ImageField(
        upload_to="images",
        verbose_name='جلوه مقاله ',
        null=True,
    )

    thumbnail = models.ImageField(
        upload_to="images",
        verbose_name='تصویر مقاله',
        null=True,
    )
    publish = models.DateTimeField(
        default=timezone.now,
        verbose_name='زمان انتشار'
    )
    creat = models.DateTimeField(
        auto_now_add=True,
    )
    update = models.DateTimeField(
        auto_now=True,
    )

    best_status = models.CharField(
        max_length=1,
        choices=BEST_STATUS_CHOICES,
        null=True,
        verbose_name='انیمه برتر ماه'
    )

    status = models.CharField(
        max_length=1,
        choices=STATUS_CHOICES,
        verbose_name='وضعیت'
    )


    class Meta:
        verbose_name = 'مقاله'
        verbose_name_plural = 'مقالات'
        ordering = ['-publish']

    def __str__(self):
        return self.title

    def jpublish(self):
        return jalali_converter(self.publish)

    jpublish.short_description = "زمان انتشار"

    def thumb_get(self):
        return format_html(f"""<img width=50 src='{self.ve_thumbnail.url}'""")

    @property
    def absolute_url(self):
        return reverse('blog:article_detail', kwargs={'slug': self.slug})

    objects = ArtManager()

blogs/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from .models import Article


def index(request, page=1):
    articles_list = Article.objects.published()
    paginator = Paginator(articles_list, 8)
    articles = paginator.get_page(page)
    context = {

        "articles": articles,
    }
    return render(request, "blogs/Anime-blog.html", context)


def detail_article(request, slug):
    published_articles = Article.objects.published()[:10]
    context = {
        "published_articles": published_articles,
        "article": get_object_or_404(Article.objects.published(), slug=slug, status="p"),

    }
    return render(request, "blogs/show-detail.html", context)


def best_in_month(request):
    context = {
        "best_in_month": Article.objects.monthly_publish()
    }
    return render(request, "blogs/top-the-month.html", context)


def about_me(request):
    return render(request, "blogs/about-me.html")

blogs/templates/blogs/Anime-blog.html
{% extends 'blogs/base.html' %}
{% load static %}

{% block main %}
    <body>
    <div class="container">
        <!-- Header Section -->
        <header>
            <!-- Include the navigation section -->
            {% include 'blogs/Nav.html' %}
        </header>
        <!-- Background Image -->
        <img class="bgn" src="{% static '/blog/image/bgn.jpg' %}" alt=""/>
        <!-- Article Section -->
        <section>

            {% for article in articles %}
                <div class="post">
                    <img class="post-bgn" src="{{ article.ve_thumbnail.url }}" alt=""/>
                    <h2 class="post-title">{{ article.title }}</h2>
                    <p class="post-desc">
                        {{ article.description_img|truncatewords:40 }}
                        <span class="post-desc2">
                                >>{{ article.description_img|truncatewords:20 }}
                            </span>
                        <button class="post-butt">
                            <a href="{% url 'blog:article_detail' article.slug %}">ادامه مطالب</a>
                        </button>
                    </p>
                </div>
            {% endfor %}
        </section>

        <!-- Footer Section -->
        {% include 'blogs/Footer.html' %}
    </div>
    </body>
{% endblock %}

blogs/templates/blogs/Footer.html
 <footer>
            <div class="footer-button">
                {% if articles.has_next %}
                    <button class="btn1">
                        <a href="{% url 'blog:index' articles.next_page_number %}">صفحه بعدی</a>
                    </button>
                {% endif %}
                {% if articles.has_previous %}
                    <button class="btn1">
                        <a href="{% url 'blog:index' articles.previous_page_number %}">صفحه قبلی</a>
                    </button>
                {% endif %}
            </div>
            <div class="footer-section">
                <!-- Social Media Links -->
                <div class="socials">
                    <a href="https://www.linkedin.com/in/pouya-marashi-3174a025b/" class="fa-brands fa-linkedin"></a>
                    <a href="https://instagram.com/anime___blog?igshid=YmMyMTA2M2Y=" class="fa-brands fa-instagram"></a>
                    <a href="https://t.me/Anime_blg" class="fa-solid fa-paper-plane"></a>
                </div>
                <!-- Footer Text -->
                <h2>Anime-blog در شبکه های اجتماعی و پیام رسان ها</h2>
            </div>
        </footer>

blogs/templates/blogs/Nav.html
<nav>
  <a href="{% url 'blog:index' %}">خانه</a>
  <a href="{% url 'blog:best_in_month' %}">انیمه های برتر ماه</a>
  <a href="{% url 'blog:about_me' %}">درباره ما</a>
  <div class="animation start-home"></div>
</nav>
<h1 class="header-title">Anime-blog</h1>

blogs/templates/blogs/about-me.html
{% load static %}
<!DOCTYPE html>
<html dir="rtl" lang="fa">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>ارتباط با ما</title>
    <link rel="stylesheet" href="{% static  'blog/css/about-me.css' %}" />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css"
    />
    <link
      href="http://awebfont.ir/css?id=1116"
      rel="stylesheet"
      type="text/css"
    />
    <link
      href="http://awebfont.ir/css?id=1939"
      rel="stylesheet"
      type="text/css"
    />
  </head>
  <body>
    <div class="container">
      <section>
        <div class="card">
          <div class="card-prof">
            <img
              class="card-bgn"
              src="{% static 'blog/image/pouya_img.jpg' %}"
              alt=""
            />
            <a href="">
              <i class="fas fa-phone" style="font-size: 20px"></i>
              تلفن :09913902045
            </a>
            <a href="">
              <i class="fas fa-at" style="font-size: 20px"></i>
              ایمیل : rsedaghate@gmail.com
            </a>
            <a href="">
              <i class="fab fa-instagram" style="font-size: 20px"></i>
              اینستاگرام :rez-sedaghati
            </a>
            <a href="">
              <i class="fab fa-telegram" style="font-size: 20px"></i>
              تلگرام :09305721819
            </a>
          </div>
          <h3 class="card-desc">
              رضا صداقتی هستم حدودا شش ماهی هست
             که وارد دنیای برنامه نویسی و طراحی
              سایت شدم درسته که شاید هنوز برنامه نویس
              عالی ای نباشم ولی برنامه نویس خوبی هستم
              که عادات عالی داره.
              01010011011101010110001101100
              011011001010111001101110011
              </h3>
        </div>
        <div class="card">
          <div class="card-prof">
            <img
              class="card-bgn"
              src="{% static 'blog/image/pouya_img.jpg' %}"
              alt=""
            />
              <a href="">
              <i class="fas fa-phone" style="font-size: 20px"></i>
              تلفن :09938656267
            </a>
            <a href="">
              <i class="fas fa-at" style="font-size: 20px"></i>
              ایمیل :pouyamarashii@gmail.com
            </a>
            <a href="">
              <i class="fab fa-instagram" style="font-size: 20px"></i>
              اینستاگرام :@_pouya._.m
            </a>
            <a href="">
              <i class="fab fa-telegram" style="font-size: 20px"></i>
              تلگرام :@pouya_MR
            </a>
          </div>
          <h3 class="card-desc">

         پویا مرعشی هستم دانشجوی رشته مهندسی کامپیوتر
         در حوضه(Backend_Development)تحصیل میکنم و
     فعالیت دارم, پایتون رو یاد گرفتم و
      درحال کامل کردن یادگیری جنگو هستم
          </h3>
        </div>
      </section>
    </div>
  </body>
</html>

blogs/templates/blogs/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fa">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Anime-blog</title>
      {% block css %}
            <link rel="stylesheet" href="{% static 'blog/css/Anime-blog.css' %}">
      {% endblock %}
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
    />
    <link
      href="http://awebfont.ir/css?id=1116"
      rel="stylesheet"
      type="text/css"
    />
    <link
      href="http://awebfont.ir/css?id=1939"
      rel="stylesheet"
      type="text/css"
    />
  </head>
  {% block main %}
    <!-- Content Goes Here -->
  {% endblock %}
</html>

blogs/templates/blogs/show-detail.html
{% extends 'blogs/base.html' %}
{% load static %}

{% block main %}
<body>
  <div class="container">
    <header>
      <!-- Navigation -->
      {% include 'blogs/Nav.html' %}
    </header>
    <img class="bgn" src="{{ article.thumbnail.url }}" alt="">
    <main>
      <!-- Article Card -->
      <div class="card">
        <div class="item">
          <img src="{{ article.ve_thumbnail.url }}" alt="">
          <h1>{{ article.title }}</h1>
          <p>{{ article.description_img|truncatewords:70 }}</p>
        </div>
      </div>
      <section class="content">
        <!-- Article Content -->
        <h1>{{ article.title }}</h1>
        <p>{{ article.description|safe }}</p>
      </section>
      <section class="menu">
        <!-- Related Articles Menu -->
        {% for article in published_articles %}
        <span style="background-image: url('{{ article.ve_thumbnail.url }}')">
          <a href="{{ article.absolute_url }}">{{ article.title }}</a>
        </span>
        {% endfor %}
      </section>
    </main>
    {% include 'blogs/Footer.html' %}
  </div>
</body>
{% endblock %}

{% block css %}
  <link rel="stylesheet" href="{% static 'blog/css/show-detail.css' %}" />
{% endblock %}

blogs/templates/blogs/top-the-month.html
{% extends 'blogs/base.html' %}
{% load static %}

{% block css %}
  <link rel="stylesheet" href="{% static 'blog/css/top-of-the-month.css' %}" />
{% endblock %}

{% block main %}
  <body>
    <div class="container">
      <header>
        <!-- Navigation -->
        {% include 'blogs/Nav.html' %}
      </header>
      <img class="bgn" src="{% static '/blog/image/best-bgn.jpg' %}" alt="" />
      <section>
        {% for top_month in best_in_month %}
          <!-- First Div -->
          <div class="first"></div>
          <!-- Post Div -->
          <div class="post">
            <div class="post-title"><h1>{{ top_month.title }}</h1></div>
            <div class="post-bgn">
              <img src="{{ top_month.ve_thumbnail.url }}" alt="" />
            </div>
            <div class="post-desc">
              <p>
                {{ top_month.description_img|truncatewords:6 }}
                <span class="post-desc2">>>{{ top_month.description_img|truncatewords:40 }}</span>
              </p>
            </div>
            <div class="post-butt">
              <button><a href="{% url 'blog:article_detail' top_month.slug %}">ادامه مطالب</a></button>
            </div>
          </div>
          <!-- Last Div -->
          <div class="last"></div>
        {% endfor %}
      </section>
      <!-- Footer -->
      {% include 'blogs/Footer.html' %}
    </div>
  </body>
{% endblock %}